### ISSUE TITLE
Running 2 `pw-volume status` at the same time causes crash

### ISSUE THREAD

**Issue by max-ishere** [smasher164/pw-volume#35]
If you run `pw-volume status & pw-volume status` (first is run in the background, second at the same time as the first one) then it crashes with

```txt
thread 'main' panicked at /home/max_ishere/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pw-volume-0.4.0/src/main.rs:395:48:
failed to unmarshal PipeWireObject: Error("trailing characters", line: 7, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/max_ishere/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pw-volume-0.4.0/src/main.rs:395:48:
failed to unmarshal PipeWireObject: Error("trailing characters", line: 7, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 2, 'pw-volume status' terminated by signal SIGABRT (Abort)

fish: Job 1, 'pw-volume status &' terminated by signal SIGABRT (Abort)
```

To be honest I have no idea why... I have 2 separate widgets (one an svg of volume, another a text of volume) and they're both on the same signal. This does not work in the current version.

```shell
$ cargo install pw-volume
# ...
Installed package `pw-volume v0.4.0` (executable `pw-volume`)
```

Tested on NixOS and Arch.

**Comment by max-ishere** [comment]
After running 2 pw-dumps and diffing their outputs the cause is just... I cant even... this is not valid JSON:
```shell
$ pw-dump >/tmp/1.txt & pw-dump >/tmp/2.txt
$ diff /tmp/1.txt /tmp/2.txt --side-by-side | tail
      }                                                               }
    }                                                               }
  }                                                               }
]                                                               ]
                                                              > [
                                                              >   {
                                                              >     "id": 56,
                                                              >     "info": null
                                                              >   }
                                                              > ]
```
That is the only difference.

**Comment by max-ishere** [comment]
I think this should be reported in pipewire, because this project isnt the cause...

**Comment by max-ishere** [comment]
I'm just gonna use `wpctl` (wireplumber)
